# Generated by Django 5.1.1 on 2024-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_animal_alter_owner_id_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
